package Vistas.VistaGrafica;


import javax.swing.*;
import java.awt.*;
import java.util.Objects;

public class VGrafic extends javax.swing.JFrame{
    /**
     * Creates new form VGrafic
     */
    public VGrafic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        bg = new javax.swing.JPanel();
        FondoTablero = new javax.swing.JPanel();
        A1 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        A6 = new javax.swing.JButton();
        A7 = new javax.swing.JButton();
        A8 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        C6 = new javax.swing.JButton();
        C7 = new javax.swing.JButton();
        C8 = new javax.swing.JButton();
        Tablero = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TextoInformativo = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoTablero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 63, 65), 1, true));
        FondoTablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A1.setText("Vacío");
        A1.setBorder(null);
        A1.setBorderPainted(false);
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        FondoTablero.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 40, 20));

        A2.setText("Vacío");
        A2.setBorder(null);
        A2.setBorderPainted(false);
        FondoTablero.add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 40, 20));

        A3.setText("Vacío");
        A3.setBorder(null);
        A3.setBorderPainted(false);
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        FondoTablero.add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 40, 20));

        A4.setText("Vacío");
        A4.setBorder(null);
        A4.setBorderPainted(false);
        FondoTablero.add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 40, 20));

        A5.setText("Vacío");
        A5.setBorder(null);
        A5.setBorderPainted(false);
        A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5ActionPerformed(evt);
            }
        });
        FondoTablero.add(A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 40, 20));

        A6.setText("Vacío");
        A6.setBorder(null);
        A6.setBorderPainted(false);
        FondoTablero.add(A6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 40, 20));

        A7.setText("Vacío");
        A7.setBorder(null);
        A7.setBorderPainted(false);
        A7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A7ActionPerformed(evt);
            }
        });
        FondoTablero.add(A7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 40, 20));

        A8.setText("Vacío");
        A8.setBorder(null);
        A8.setBorderPainted(false);
        FondoTablero.add(A8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 40, 20));

        B1.setText("Vacío");
        B1.setBorder(null);
        B1.setBorderPainted(false);
        FondoTablero.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 40, 20));

        B2.setText("Vacío");
        B2.setBorder(null);
        B2.setBorderPainted(false);
        FondoTablero.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 40, 20));

        B3.setText("Vacío");
        B3.setBorder(null);
        B3.setBorderPainted(false);
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        FondoTablero.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 40, 20));

        B4.setText("Vacío");
        B4.setBorder(null);
        B4.setBorderPainted(false);
        FondoTablero.add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 40, 20));

        B5.setText("Vacío");
        B5.setBorder(null);
        B5.setBorderPainted(false);
        FondoTablero.add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 40, 20));

        B6.setText("Vacío");
        B6.setBorder(null);
        B6.setBorderPainted(false);
        FondoTablero.add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 40, 20));

        B7.setText("Vacío");
        B7.setBorder(null);
        B7.setBorderPainted(false);
        FondoTablero.add(B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 40, 20));

        B8.setText("Vacío");
        B8.setBorder(null);
        B8.setBorderPainted(false);
        FondoTablero.add(B8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 40, 20));

        C1.setText("Vacío");
        C1.setBorder(null);
        C1.setBorderPainted(false);
        FondoTablero.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 40, 20));

        C2.setText("Vacío");
        C2.setBorder(null);
        C2.setBorderPainted(false);
        FondoTablero.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 40, 20));

        C3.setText("Vacío");
        C3.setBorder(null);
        C3.setBorderPainted(false);
        FondoTablero.add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 40, 20));

        C4.setText("Vacío");
        C4.setBorder(null);
        C4.setBorderPainted(false);
        FondoTablero.add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 40, 20));

        C5.setText("Vacío");
        C5.setBorder(null);
        C5.setBorderPainted(false);
        FondoTablero.add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 40, 20));

        C6.setText("Vacío");
        C6.setBorder(null);
        C6.setBorderPainted(false);
        FondoTablero.add(C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 40, 20));

        C7.setText("Vacío");
        C7.setBorder(null);
        C7.setBorderPainted(false);
        FondoTablero.add(C7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 40, 20));

        C8.setText("Vacío");
        C8.setBorder(null);
        C8.setBorderPainted(false);
        FondoTablero.add(C8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 40, 20));

        //Mio
        Icon iconTablero = new ImageIcon("Vistas/VistaGrafica/Imagenes/tablero.jpg");
        ImageIcon iconFondo = new ImageIcon("Vistas/VistaGrafica/Imagenes/Fondo.png");
        Tablero.setIcon(iconTablero); // NOI18N
        FondoTablero.add(Tablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -40, 460, -1));

        bg.add(FondoTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 490, 350));

        Fondo.setIcon(new javax.swing.ImageIcon(iconFondo.getImage())); // NOI18N
        bg.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 650, 470));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TextoInformativo, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 20, Short.MAX_VALUE)
                                .addComponent(TextoInformativo))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 490, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void A5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void A7ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VGrafic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VGrafic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VGrafic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VGrafic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VGrafic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton A1;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton A6;
    private javax.swing.JButton A7;
    private javax.swing.JButton A8;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton C1;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton C5;
    private javax.swing.JButton C6;
    private javax.swing.JButton C7;
    private javax.swing.JButton C8;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel FondoTablero;
    private javax.swing.JLabel Tablero;
    private javax.swing.JLabel TextoInformativo;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration
}


