package Vistas;

public enum EstadosVista {ESPERANDOCONEXION,
    INGRESARFICHA,
    SACARFICHA,
    MOVERFICHA,
    MOVERFICHA2DAFASE,
    INGRESONOMBRE,
    BLOQUEADA,
    MENU,
    REINICIARJUEGO
}
